outputFormats:
  jsonfeed:
    mediaType: "application/json"
    baseName: "feed"
    isPlainText: true
  podcast:
    mediaType: "application/rss+xml"
    baseName: "podcast"

module:
  imports:
    - path: github.com/twitter/twemoji
      mounts:
        - source: assets/svg
          target: static/twemoji/svg

  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
